### ISSUE TITLE
Is KUESTA is still in active developement ?

### ISSUE THREAD

**Issue by frederic-loui** [nttcom/kuesta#289]
Thanks for writing this software. Adopting `gitops` principle is a brilliant idea. Is KUESTA still under active development ?

**Comment by Tatsuki3939** [comment]
Thank you for your inquiry. This software is scheduled for a major update in July. Thank you for your cooperation.

**Comment by Tatsuki3939** [comment]
Thank you for your inquiry. This software is scheduled for a major update in July. Thank you for your cooperation.
